const fs = require('node:fs')
const path = require('node:path')
const { app, BrowserWindow } = require('electron')

const root = process.cwd()
const userData = path.join(root, '.test-user-data')
fs.mkdirSync(userData, { recursive: true })
app.setPath('userData', userData)

app.whenReady().then(async () => {
  const active = process.argv.includes('--active')
  const win = new BrowserWindow({ width: 1440, height: 900, show: true, backgroundColor: '#f7d1c8', webPreferences: active ? { preload: path.join(root, 'scripts', 'mock-preload.cjs'), contextIsolation: true, webviewTag: true, backgroundThrottling: false } : {} })
  await win.loadFile(path.join(root, 'dist', 'index.html'))
  await new Promise((resolve) => setTimeout(resolve, 1200))
  if (!active && process.argv.includes('--compatible')) {
    await win.webContents.executeJavaScript('document.querySelectorAll(\'.provider-switch button\')[1].click()')
    await new Promise((resolve) => setTimeout(resolve, 300))
  }
  const image = await win.webContents.capturePage()
  const output = path.join(root, 'artifacts', active ? 'active-desktop.png' : process.argv.includes('--compatible') ? 'compatible-setup.png' : 'first-run.png')
  fs.mkdirSync(path.dirname(output), { recursive: true })
  fs.writeFileSync(output, image.toPNG())
  console.log(output)
  if (active) {
    await win.webContents.executeJavaScript('document.querySelector(\'[aria-label="Open Command"]\').click()')
    await new Promise((resolve) => setTimeout(resolve, 350))
    const second = await win.webContents.capturePage()
    const commandOutput = path.join(root, 'artifacts', 'command-window.png')
    fs.writeFileSync(commandOutput, second.toPNG())
    console.log(commandOutput)
    await win.webContents.executeJavaScript('document.querySelector(\'[aria-label="Open Browser"]\').click()')
    await new Promise((resolve) => setTimeout(resolve, 350))
    const third = await win.webContents.capturePage()
    const browserOutput = path.join(root, 'artifacts', 'browser-window.png')
    fs.writeFileSync(browserOutput, third.toPNG())
    console.log(browserOutput)
    await win.webContents.executeJavaScript('document.querySelector(\'header [aria-label="Settings"]\').click()')
    await new Promise((resolve) => setTimeout(resolve, 350))
    const fourth = await win.webContents.capturePage()
    const settingsOutput = path.join(root, 'artifacts', 'provider-settings.png')
    fs.writeFileSync(settingsOutput, fourth.toPNG())
    console.log(settingsOutput)
  }
  app.quit()
})
